version: "3.8"

services:
  #change if you want to create several different containers
  rpi-zero-dev2:
    build:
      context: .
      args:
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
    image: rpi-zero-dev:latest
    #change if you want to create several different containers
    container_name: rpi-zero-dev2
    networks:
      - iotnet
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - TZ=UTC
      - LANG=sv_SE.UTF-8
      - LC_ALL=sv_SE.UTF-8
    ports:
      - "2224:22"
      #- "1883:1883" 
    volumes:
      - ./app:/app
    restart: unless-stopped

networks:
   iotnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1
